# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: centos_playground/pkg_survey/result*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # - id: check-added-large-files  # this is a research repo, we can have big files here
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
        exclude: tests/integration/conftest.py
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --per-file-ignores=ps_deployment/src/files/packit.wsgi:F401
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v0.782
  #    hooks:
  #      - id: mypy
  #        args: [--no-strict-optional, --ignore-missing-imports]
  - repo: https://github.com/packit/pre-commit-hooks
    rev: 3bf9afc5ede12a4ee26e9451f306edf255749396
    hooks:
      - id: check-rebase
        args:
          - https://github.com/packit/research.git
        stages: [manual, push]
